// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldwewokhecgdxflifdgx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkd2V3b2toZWNnZHhmbGlmZGd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzQyNDYsImV4cCI6MjA2OTcxMDI0Nn0.x-gryp9YIQ9AMlplr4P_YAjehMlS9wAtsSXBrDP8xys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});